name: Go tests

on:
  workflow_call:

jobs:
  cluster-test:
    runs-on: "blacksmith-16vcpu-ubuntu-2204"
    # OIDC token auth for Depot & AWS
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/go
      - uses: ./.github/actions/tilt
        with:
          depot-project-id: ${{ vars.DEPOT_PROJECT_ID }}
      - run: bin/cluster-test.sh bash -c 'cd go && make test'
      - name: Save service logs to artifact
        if: always()
        uses: ./.github/actions/export-tilt-logs
        with:
          artifact-name: "go-cluster-test"
